import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styled from '@emotion/styled'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>고영이메모장</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <StyledLink href={'/about'}>about 페이지</StyledLink>
        </div>
        <Content>
          Hello world!
          <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
        </Content>
      </main>
    </div>
  )
}

export default Home

const StyledLink = styled(Link)`
  color: red;
  background: white;
  text-decoration: underline;
`

const Content = styled.div`
  background: blue;
  font-size: 20px;
`
