import Head from 'next/head'
import Splash from '../component/splash'
import { useEffect, useRef, useState } from 'react'
import GlobalStyle from '../styles/GlobalStyle'

export default function Home() {
  const [visibleSplash, setVisibleSplash] = useState(true)
  const [removeSplash, setRemoveSplash] = useState(false)
  const timeoutId = useRef<NodeJS.Timeout>()

  useEffect(() => {
    timeoutId.current = setTimeout(() => {
      setVisibleSplash(false)
      setTimeout(() => {
        setRemoveSplash(true)
      }, 300)
    }, 1000 * 2)
    return () => {
      clearTimeout(timeoutId.current)
    }
  }, [])

  return (
    <div>
      <Head>
        <title>고영이메모장</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GlobalStyle />
      {!removeSplash && <Splash visible={visibleSplash} />}
      <main>Hello world!</main>
    </div>
  )
}
